//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace instance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concept
    {
        public int id { get; set; }
        public string firstconcept { get; set; }
        public string secondconcept { get; set; }
        public string thirdconcept { get; set; }
        public string concepturl { get; set; }
    }
}
